### ISSUE TITLE
Import scss/sass files from js/jsx file fails

### ISSUE THREAD

**Issue by crdil** [rshurts/yak-shears#1]
Nice clean boilerplate, using it to learn React :)
I have an issue though, when I try to import scss/sass files from a js/jsx file the scss file won't get compiled. Instead I get this error
```
Module parse failed: /home/kristoffer/dev/web/projects/react-jwt/app/style/dashboard.scss Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:0)...
```

How can I fix this so I can import the needed scss/css files from js files directly instead of importing them from main.scss or adding them to the webpack config one by one?
Thanks

**Comment by crdil** [comment]
I just noticed that it works when I import like this

```
import '!css-loader!sass-loader!../../style/dashboard.scss';
```

But would be nice to be able to import without the loaders as a prefix

**Comment by rshurts** [comment]
The current webpack config doesn't expect any scss/sass embedded in the jsx. It was a use case I built for. 

With that said, I plan on rebuilding this with webpack 2 and the latest react router. I'll take a look at cleaning things up then.
